kind: Pod
apiVersion: v1
metadata:
  name: pvc-inspector
spec:
  containers:
    - resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      name: minio-client
      env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-data-integration-pipeline-datastore
              key: minioAccessKey
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-data-integration-pipeline-datastore
              key: minioSecretKey
      imagePullPolicy: Always
      volumeMounts:
        - name: bgeo-configs
          mountPath: /data
        - name: bgeo-configs
          mountPath: /.mc
      image: >-
        image-registry.openshift-image-registry.svc:5000/988040-tools/minio-client-monitor:latest
      args:
      - -C
      - /data
      - server
      - /data
  volumes:
    - name: bgeo-configs
      persistentVolumeClaim:
        claimName: bgeo-configs
    - name: bgeo-mc
      persistentVolumeClaim:
        claimName: bgeo-mc
