apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: ols-admin-sidecar
  name: ols-admin-sidecar
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: 'ols-admin-sidecar:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM tomcat:9-jdk11-openjdk-slim-bullseye
      RUN mkdir /usr/local/tomcat/webapps/int
      WORKDIR "/usr/local/tomcat/webapps/int"
      COPY ols-admin.war /usr/local/tomcat/webapps/int/int.war
      RUN jar -xvf int.war
      WORKDIR "/usr/local/tomcat/"
      RUN mv /usr/local/tomcat/webapps/int/int.war /usr/local/tomcat/webapps/
      RUN sed -i 's@<Connector @<Connector maxHttpHeaderSize="65536" @g' /usr/local/tomcat/conf/server.xml
    type: Dockerfile
  strategy:
    type: Docker
    dockerStrategy: {}
  successfulBuildsHistoryLimit: 5
