apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: geocoder-sidecar
  name: geocoder-sidecar
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'geocoder-sidecar:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM tomcat:9-jdk11-openjdk-slim-bullseye
      RUN mkdir /usr/local/tomcat/webapps/ROOT
      WORKDIR "/usr/local/tomcat/webapps/ROOT"
      COPY geocoder.war /usr/local/tomcat/webapps/ROOT/ROOT.war
      RUN jar -xvf ROOT.war
      WORKDIR "/usr/local/tomcat/"
      RUN mv /usr/local/tomcat/webapps/ROOT/ROOT.war /usr/local/tomcat/webapps/
    type: Dockerfile
  strategy:
    type: Docker
    dockerStrategy: {}
  successfulBuildsHistoryLimit: 5
