name: OpenAPI Spec

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: "Java version to use"
        required: false
        default: "17"

jobs:
  generate-and-lint:
    name: Generate & Lint OpenAPI Spec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
